// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Image struct {
	Name      string      `json:"name"`
	URL       string      `json:"url"`
	Variables []*Variable `json:"variables"`
}

type Variable struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Default     *string `json:"default"`
	Required    bool    `json:"required"`
	Uncommon    bool    `json:"uncommon"`
}
